name: Deploy Terraform Infrastructure

on:
  push:
    branches: [ "main" ] # Only trigger on pushes to the 'main' branch
  pull_request:
    branches: [ "main" ] # Only trigger on pull requests to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2
    
    - name: Create Private Key File
      run: |
        echo "${{ secrets.PRIVATE_KEY_FILE }}" > private_key.pem

    - name: Login to Oracle Cloud Infrastructure
      run: |
        export TF_VAR_tenancy_ocid="${{ secrets.TF_VAR_TENANCY_OCID }}"
        export TF_VAR_user_ocid="{{ secrets.TF_VAR_USER_OCID }}"
        export TF_VAR_fingerprint="{{ secrets.TF_VAR_FINGERPRINT }}"
        export TF_VAR_region="{{ secrets.TF_VAR_region }}"

        # terraform login \
        #   --hostname "https://-1.oraclecloud.com" \
        #   --provider oci \
        #   --user-ocid "$TF_VAR_user_ocid" \
        #   --tenancy-ocid "$TF_VAR_tenancy_ocid" \
        #   --fingerprint "$TF_VAR_fingerprint" \
        #   --private-key-file "./private_key.pem"

    - name: Initialize Terraform
      run: terraform init

    - name: Plan
      run: terraform plan -out=plan

    - name: Apply
      run: terraform apply -auto-approve plan