name: Deploy Terraform Infrastructure

on:
  push:
    branches: [ "main" ] # Only trigger on pushes to the 'main' branch
  pull_request:
    branches: [ "main" ] # Only trigger on pull requests to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2

    - name: Login to Oracle Cloud Infrastructure
      run: |
        export TF_VAR_tenancy_ocid="<your_tenancy_ocid>"
        export TF_VAR_user_ocid="<your_user_ocid>"
        export TF_VAR_fingerprint="<your_fingerprint>"
        export TF_VAR_private_key_path="./path/to/your/private/key" 

        terraform login \
          --hostname "https://api.us-ashburn-1.oraclecloud.com" \
          --provider oci \
          --user-ocid "$TF_VAR_user_ocid" \
          --tenancy-ocid "$TF_VAR_tenancy_ocid" \
          --fingerprint "$TF_VAR_fingerprint" \
          --private-key-file "$TF_VAR_private_key_path"

    - name: Initialize Terraform
      run: terraform init

    - name: Plan
      run: terraform plan -out=plan

    - name: Apply
      run: terraform apply -auto-approve plan